import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import chatsRouter from "./chats";
import memoryRouter from "./memory";
import modelsRouter from "./models";
import baseMcpRouter from "./base-mcp";
import settingsRouter from "./settings";
import protocolsRouter from "./protocols";
import actionsRouter from "./actions";
import workflowsRouter from "./workflows";
import tokensRouter from "./tokens";
import perpsRouter from "./perps";
import portfolioRouter from "./portfolio";
import coinstatsRouter from "./coinstats";
import bunnyRouter from "./bunny";
import bunnydsRouter from "./bunnyds";
import telegramRouter from "./telegram";
import storageRouter from "./storage";
import authRouter from "./auth";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(chatRouter);
router.use(chatsRouter);
router.use(memoryRouter);
router.use(modelsRouter);
router.use(baseMcpRouter);
router.use(settingsRouter);
router.use(protocolsRouter);
router.use(actionsRouter);
router.use(workflowsRouter);
router.use(tokensRouter);
router.use(perpsRouter);
router.use(portfolioRouter);
router.use(coinstatsRouter);
router.use(bunnyRouter);
router.use(bunnydsRouter);
router.use(telegramRouter);
router.use(storageRouter);

export default router;
