import { useEffect } from "react";
import {
  useHealthCheck,
  getGetBaseMcpStatusQueryKey,
} from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";
import { cn } from "@/lib/utils";
import logo from "@assets/logo.png";
import { useAuth } from "@/hooks/useAuth";
import { useT, useLang } from "@/i18n";
import { SELECTABLE_LANGS, LANG_LABELS, type Lang } from "@/i18n/config";

export function TopBar() {
  const queryClient = useQueryClient();
  const auth = useAuth();
  const t = useT();
  const { lang, setLang } = useLang();
  const { data: healthData, isError: isHealthError } = useHealthCheck({
    query: { queryKey: ["/api/healthz"], refetchInterval: 5000 },
  });

  useEffect(() => {
    const onMessage = (ev: MessageEvent) => {
      if (ev.data?.type === "base-mcp-auth") {
        // Anon → real user upgrade also lands here: refresh both auth and
        // mcp status so the UI flips from "connect" to "signed in".
        void auth.refresh();
        queryClient.invalidateQueries({ queryKey: getGetBaseMcpStatusQueryKey() });
      }
    };
    window.addEventListener("message", onMessage);
    return () => window.removeEventListener("message", onMessage);
  }, [queryClient, auth]);

  // Persist the language choice server-side so background action
  // recommendations/alerts (generated by the scanner with no browser to read
  // from) are produced natively in this language. Fire-and-forget; ignores the
  // 401 when not signed in.
  const persistLang = (l: Lang) => {
    void fetch("/api/settings/lang", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ lang: l }),
    }).catch(() => {});
  };

  // Once authenticated, push the current (browser-stored) language up so the
  // server's preference matches what the user sees, even if they never touch
  // the switcher this session.
  useEffect(() => {
    if (auth.authenticated) persistLang(lang);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [auth.authenticated]);

  const isConnected = healthData?.status === "ok" && !isHealthError;

  return (
    <div className="h-14 sm:h-16 w-full flex items-center justify-between px-3 sm:px-4 border-b border-border bg-background shrink-0">
      <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity" aria-label="BunnyOS home">
        <img src={logo} alt="logo" className="h-9 sm:h-12 w-auto" />
      </Link>

      <div className="flex items-center gap-2">
        <label className="sr-only" htmlFor="lang-select">
          {t("topbar.language")}
        </label>
        <select
          id="lang-select"
          value={lang}
          onChange={(e) => {
            const next = e.target.value as Lang;
            setLang(next);
            persistLang(next);
          }}
          aria-label={t("topbar.language")}
          className="px-2 py-1 sm:px-2.5 sm:py-2 border border-border/70 text-foreground bg-background hover:bg-foreground/5 rounded font-sans text-xs font-medium transition-colors cursor-pointer"
          data-testid="select-language"
        >
          {SELECTABLE_LANGS.map((l) => (
            <option key={l} value={l}>
              {LANG_LABELS[l]}
            </option>
          ))}
        </select>
        <a
          href="https://app.virtuals.io/virtuals/80805"
          target="_blank"
          rel="noreferrer"
          className="px-2 py-1 sm:px-3 sm:py-2 border border-border/70 text-foreground hover:bg-foreground/5 rounded font-sans text-xs font-medium transition-colors inline-flex items-center justify-center gap-1.5"
          data-testid="link-support-virtuals-header"
        >
          {t("topbar.supportOnVirtuals")}
        </a>
        {auth.authenticated && auth.walletAddress && (
          <button
            onClick={() => void auth.logout()}
            className="px-2 py-1 sm:px-3 sm:py-2 bg-foreground/10 text-foreground hover:bg-foreground/20 rounded font-sans text-xs font-medium transition-colors inline-flex items-center justify-center gap-1.5"
          >
            {t("common.signOut")}
          </button>
        )}
        <div
          className={cn(
            "w-2 h-2 rounded-full ml-2",
            isConnected ? "bg-green" : "bg-red"
          )}
          title={isConnected ? t("common.connected") : t("common.disconnected")}
        />
      </div>
    </div>
  );
}
